// Curated fallback portfolio shown whenever the database holds no entries yet.
// Shared by prisma/seed.ts (build-time) and GET /api/portfolio (runtime safety
// net), so the gallery never depends on a runtime write.
export const DEFAULT_PORTFOLIO = [
  {
    title: 'South India Indie Rock Tour 2026',
    category: 'concert',
    location: 'YMCA Grounds, Chennai',
    crowd: '8,000+ Attendees',
    specs: '16-Box Flown Line Array, 24 Moving Heads, Dual 18" Subs',
    tag: 'Arena Concert',
    mediaType: 'video',
    mediaUrl: '/assets/Viedos/05_gallery_20261005103713.mp4',
    thumbnailUrl: '/assets/images/keyframes/image10_gallery_start.jpg',
    sortOrder: 1,
  },
  {
    title: 'Royal Chettinad Destination Wedding',
    category: 'wedding',
    location: 'Karaikudi Palace Grounds',
    crowd: '1,500 Guests',
    specs: 'Tungsten 3200K Stage Wash, Wireless Mics, Walnut Stage Deck',
    tag: 'Luxury Wedding',
    mediaType: 'image',
    mediaUrl: '/assets/images/keyframes/image08_packages_start.jpg',
    thumbnailUrl: '/assets/images/keyframes/image08_packages_start.jpg',
    sortOrder: 2,
  },
  {
    title: 'Mega Tech Summit Keynote & Expo',
    category: 'corporate',
    location: 'Chennai Trade Centre, Nandambakkam',
    crowd: '3,500 Delegates',
    specs: 'Speech Intelligibility DSP, Digital Mics, Low-Profile Truss',
    tag: 'Corporate Summit',
    mediaType: 'video',
    mediaUrl: '/assets/Viedos/03_services_20261005103713.mp4',
    thumbnailUrl: '/assets/images/keyframes/image06_services_start.jpg',
    sortOrder: 3,
  },
  {
    title: 'Inter-College Cultural Music Fest',
    category: 'college',
    location: 'Loyola College Grounds, Chennai',
    crowd: '12,000+ Students',
    specs: 'Full Arena Ground Stack, Subwoofer Wall, CO2 Blasters',
    tag: 'College Fest',
    mediaType: 'video',
    mediaUrl: '/assets/Viedos/01_home_20261005103713.mp4',
    thumbnailUrl: '/assets/images/keyframes/image01_anchor_lineup.jpg',
    sortOrder: 4,
  },
  {
    title: 'Sunburn Campus EDM Night Showcase',
    category: 'concert',
    location: 'PSG Tech Campus, Coimbatore',
    crowd: '6,500 Attendees',
    specs: 'Subwoofer Array, DMX Beam Fixtures, High-Output Hazers',
    tag: 'EDM Concert',
    mediaType: 'image',
    mediaUrl: '/assets/images/keyframes/image11_gallery_end.jpg',
    thumbnailUrl: '/assets/images/keyframes/image11_gallery_end.jpg',
    sortOrder: 5,
  },
  {
    title: 'Grand Classical Temple Arangetram',
    category: 'wedding',
    location: 'Meenakshi Amman Hall, Madurai',
    crowd: '2,000 Devotees',
    specs: 'Zero Acoustic Feedback Calibration, Shure Ribbon Mics',
    tag: 'Acoustic Heritage',
    mediaType: 'image',
    mediaUrl: '/assets/images/keyframes/image04_about_start.jpg',
    thumbnailUrl: '/assets/images/keyframes/image04_about_start.jpg',
    sortOrder: 6,
  },
] as const;
